### ISSUE TITLE
Protection Paladin Implementation

### ISSUE THREAD

**Issue by wsphillips** [wowsims/sod#1024]
This issue is a tracker for all the talents, runes, abilities, and items/item sets associated with the Protection Paladin sim I have been working on. I will keep the list updated with links to PRs as they get submitted. Each item will be checked off when it is reviewed and merged.

## UI Auras/Options
- [x] Blessing of Sanctuary #1071 
- [x] Righteous Fury #1064 
- [x] Forbearance #1048 

## Abilities
- [x] Holy Shield #1031 
- [x] Shield of Righteousness #1028 
- [x] Divine Protection (MP) #1048 
- [x] Avenger's Shield #1038 
- [x] Lay on Hands #1080 
- [x] Hammer of the Righteous #1036 

## Talents
- [x] Shield Specialization/Anticipation #1027 
- [x] Redoubt #1029 
- [x] Reckoning #1030 
- [x] Improved Righteous Fury #1064 
- [x] Improved Lay on Hands #1080 

## Runes
- [x] Aegis #1049 
- [x] Malleable Protection #1048 
- [x] Improved Sanctuary #1071 
- [x] Hand of Reckoning (passive effects) #1064 

## Item Sets
- [x] T1/T2 Item set bonuses #1051 

## Items
- [x] Libram of Avengement / Libram of the Devoted #1066 

## Core
- [x] Correction to SBV Multiplier
#1025
#1077 
## Finalization
- [ ] Update APLs, gear sets, default consumes/buffs and EP weights #1112

**Comment by martijngonlag** [comment]
@wsphillips this is great, thank you for implementing this, I have been looking forward to having access to this!

As I am starting to use this, I had a couple of questions -- my apologies in advance if this is not the right place to raise these.

1. Does this consider the Truthbearer proc?
2. Is it possible to include [Iron Counterweight](https://www.wowhead.com/classic/item=6043/iron-counterweight) as an enchant for Truthbearer? A fellow guildie who has the weapon informed me that you can apply a 2h enchant on it, and it will remain on when you swap to 1h.
