### ISSUE TITLE
TODO: Implement new profession items and effects

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/sod#160]
- [x] Alchemy
  - [x] https://www.wowhead.com/classic/item=215162/mildly-irradiated-rejuvenation-potion
    - https://github.com/wowsims/sod/pull/209
- [x] Blacksmithing
  - [x] https://www.wowhead.com/classic/item=215167/reflective-truesilver-braincage
    - Nothing to do
  - [x] https://www.wowhead.com/classic/item=215161/tempered-interference-negating-helmet
- [x] Enchanting
  - [x] https://www.wowhead.com/classic/spell=435903/enchant-chest-retricutioner
  - [x] https://www.wowhead.com/classic/spell=435481/enchant-weapon-dismantle
    - https://github.com/wowsims/sod/pull/183
- [x] Engineering
  - [x] https://www.wowhead.com/classic/item=215168/ez-thro-radiation-bomb
  - [x] https://www.wowhead.com/classic/item=215127/high-yield-radiation-bomb
  - [x] https://www.wowhead.com/classic/item=215115/hyperconductive-goldwrap
  - [x] https://www.wowhead.com/classic/item=213390/whirling-truesilver-gearwall
    - Nothing to do
- [x] Leatherworking
  - [x] https://www.wowhead.com/classic/item=215166/glowing-gneuro-linked-cowl
  - [x] https://www.wowhead.com/classic/item=215114/glowing-hyperconductive-scale-coif
  - [x] https://www.wowhead.com/classic/item=215381/gneuro-conductive-channelers-hood
  - [x] https://www.wowhead.com/classic/item=215382/rad-resistant-scale-hood
- [x] Tailoring
  - [x] https://www.wowhead.com/classic/item=215111/gneuro-linked-arcano-filament-monocle

**Comment by kayla-glick** [comment]
Added remaining epics with https://github.com/wowsims/sod/pull/176
