### ISSUE TITLE
TODO: Update consumes lists for Phase 2

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/sod#161]
- [x] Potions
  - [x] https://www.wowhead.com/classic/item=215162/mildly-irradiated-rejuvenation-potion
    - https://github.com/wowsims/sod/pull/209
- [x] Foods
  - [x] Dragonbreath Chili https://github.com/wowsims/sod/pull/181
- [x] Weapon Imbues
- https://github.com/wowsims/sod/pull/175
- https://github.com/wowsims/sod/pull/169
- [x] Elixirs
- https://github.com/wowsims/sod/pull/144
- [x] Explosives
  - [x] Solid Dynamite
  - [x] New phase 2 explosives
