### ISSUE TITLE
TODO Gear Effects

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/sod#201]
Check these off as you complete them please! Feel free to add any items that aren't already listed.

### Armor
- [x] [Electromagnetic Hyperflux Reactivator](https://www.wowhead.com/classic/item=213281/electromagnetic-hyperflux-reactivator)
  - Implemented but may needs information on how the damage works

### Trinkets
- [x] [Rune of Perfection](https://www.wowhead.com/classic/search?q=rune+of+perfection) (both ranks)
- [x] [Ancestral Bloodstorm Beacon](https://www.wowhead.com/classic/item=216615/ancestral-bloodstorm-beacon)
- [x] [Miniaturized Combustion Chamber](https://www.wowhead.com/classic/item=213347/miniaturized-combustion-chamber)
- [x] [Gyromatic Experiment 420b](https://www.wowhead.com/classic/item=213348/gyromatic-experiment-420b)
- [x] [Domesticated Attack Chicken](https://www.wowhead.com/classic/item=215461/domesticated-attack-chicken)

### Weapons
- [x] [Nightblade](https://www.wowhead.com/classic/item=1982/nightblade)
- [x] [Automatic Crowd Pummeler](https://www.wowhead.com/classic/item=210741/automatic-crowd-pummeler)
- [x] [Fiery War Axe](https://www.wowhead.com/classic/item=870/fiery-war-axe)
- [x] [Ravager](https://www.wowhead.com/classic/item=7717/ravager)
- [x] [Bloodlash Bow](https://www.wowhead.com/classic/item=216516/bloodlash-bow)
- [x] [Mekkatorque's Arcano-Shredder](https://www.wowhead.com/classic/item=213409/mekkatorques-arcano-shredder)
- [x] [Supercharged Headchopper](https://www.wowhead.com/classic/item=213296/supercharged-headchopper)
- [x] [Shawarmageddon](https://www.wowhead.com/classic/item=213105/shawarmageddon)
- [x] [Pendulum of Doom](https://www.wowhead.com/classic/item=9425/pendulum-of-doom)
- [x] [The Jackhammer](https://www.wowhead.com/classic/item=9423/the-jackhammer)
- [x] [Gut Ripper](https://www.wowhead.com/classic/item=2164/gut-ripper)

**Comment by TheGroxEmpire** [comment]
Ravager: https://github.com/wowsims/sod/pull/223

**Comment by rosenrusinov** [comment]
Rune of Perfection should already be parsed as its the generic regex for spell pen which i have updated @kayla-glick

**Comment by FelixPflaum** [comment]
Automatic Crowd Pummeler was included in https://github.com/wowsims/sod/pull/171

**Comment by FelixPflaum** [comment]
Miniaturized Combustion Chamber will be in https://github.com/wowsims/sod/pull/247

**Comment by rosenrusinov** [comment]
Bloodlash Bow added in #255

**Comment by rosenrusinov** [comment]
Mekkatorque's Arcano-Shredder added in #287

**Comment by FelixPflaum** [comment]
Nightblade, Fiery War Axe, Bloodstorm Beacon and Combustion chamber added in https://github.com/wowsims/sod/pull/247

**Comment by Scottfj** [comment]
May I please request that Supercharged Head Chopper is added to this list?
[](https://www.wowhead.com/classic/item=213296/supercharged-headchopper#dropped-by)
Thanks!

**Comment by FelixPflaum** [comment]
@Scottfj Does it not work? Its proc was also added in https://github.com/wowsims/sod/pull/247

**Comment by Scottfj** [comment]
@FelixPflaum I've just tried it again, you're correct it does work, but it shows in the results as "Lightning Bolt (Rank 1)" rather than a unique name, which is why I didn't spot it originally. My apologies, and thanks for looking into it :).

**Comment by rosenrusinov** [comment]
"Lightning Bolt (Rank 1)" is the name of the spell that is cast in-game as well

**Comment by TheGroxEmpire** [comment]
Shawarmageddon #338

**Comment by FelixPflaum** [comment]
[Pendulum of Doom](https://www.wowhead.com/classic/item=9425/pendulum-of-doom)
[The Jackhammer](https://www.wowhead.com/classic/item=9423/the-jackhammer)
[Gut Ripper](https://www.wowhead.com/classic/item=2164/gut-ripper)

in https://github.com/wowsims/sod/pull/375

**Comment by sanguinerarogue** [comment]
#491 for the final trinket (attack chicken implemented earlier.
